---
- name: Test Playbook for Ansible Roles
  hosts: all
  gather_facts: false
  tasks:
    # - name: Install python library for database
    #   ansible.builtin.pip:
    #     name: psycopg2-binary
    #     state: present
    #   delegate_to: localhost

    - name: Include role name for Testing
      include_role:
        name: ansible-role-ping-test
