---
- name: Fetch Endpoint Credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Include role name to Fetch Endpoint Credentials
      include_role:
        name: ansible-role-fetch-endpoint-credentials

- name: Ansible Playbook - Roles Testing
  hosts: all
  tasks:
    - name: Include role name for Testing
      include_role:
        name: ansible-role-ping-test
