---
- name: ansible-role-fetch-endpoint-credentials
  src: git+https://github.com/Ansible-ServerAutomation/ansible-role-fetch-endpoint-credentials.git
  version: development

- name: execution_result
  src: git+https://github.com/Ansible-ServerAutomation/ansible-role-execution-result.git
  version: development

- name: ansible-role-ping-test
  src: git+https://github.com/Ansible-ServerAutomation/ansible-role-ping-test.git
  version: development

- name: update-db
  src: git+https://github.com/Ansible-ServerAutomation/ansible-role-execution-result-update-db.git
  version: development